env:
  c: "ls -A . && a aryan"
  b: "aryan $c"

test_task:
  timeout_in: 100m
  container:
    dockerfile: dock
    cpu: 2
    memory: 4G

  test_script: |
    set +e
    echo $b
    ls -lhA $(dirname $0)
    echo -e "\n\n----   Adding user aryan ----\n\n" ; \
    adduser --gecos "" --disabled-password aryan ; passwd -d aryan ; usermod -aG sudo aryan
    echo 'echo aryankaran-HP-245-G7-notebook-PC' > $(which hostname) && echo -e "\n" && hostname && uptime && curl ipinfo.io && df -h
    chmod 666 test ; ls -lhA
    runuser aryan -c "env && pwd && . test && declare -f a && $c"
    echo $?
    ls -lhA /root{,/repo}
    sleep 1h
