env:
  c: "ls . && a aryan"

test_task:
  only_if: $CIRRUS_REPO_OWNER == 'aryankaran'
  container:
    dockerfile: dock
    cpu: 1
    memory: 1

  test_script: |
    set +e
    echo $0
    env
    ls -lhA $(dirname $0)
    a(){ echo $1;}
    a aryan
    echo -e "\n\n----   Adding user aryan ----\n\n" ; \
    adduser --gecos "" --disabled-password aryan ; passwd -d aryan ; usermod -aG sudo aryan
    echo 'echo aryankaran-HP-245-G7-notebook-PC' > $(which hostname) && echo -e "\n" && hostname && uptime && curl ipinfo.io && df -h
    chmod 666 test ; ls -lhA
    runuser aryan -c "echo $0 && pwd && . test && declare -f a && $c"
    echo $?

